line 2 "top.tlv" 0 //_\TLV_version 1d: tl-x.org, generated by SandPiper(TM) 1.14-2022/10/10-beta-Pro
`line 9 "top.tlv" 1
//_\SV
   // Macro providing required top-level module definition, random
   // stimulus support, and Verilator config.
   module top(input wire clk, input wire reset, input wire [31:0] cyc_cnt, output wire passed, output wire failed);    /* verilator lint_save */ /* verilator lint_off UNOPTFLAT */  bit [256:0] RW_rand_raw; bit [256+63:0] RW_rand_vect; pseudo_rand #(.WIDTH(257)) pseudo_rand (clk, reset, RW_rand_raw[256:0]); assign RW_rand_vect[256+63:0] = {RW_rand_raw[62:0], RW_rand_raw};  /* verilator lint_restore */  /* verilator lint_off WIDTH */ /* verilator lint_off UNOPTFLAT */   // (Expanded in Nav-TLV pane.)
`line 19 "top.tlv" 1

`include "top_gen.sv" //_\TLV
   assign L0_reset_a0 = reset;
   `line 14 "top.tlv" 1   // Instantiated from top.tlv, 22 as: m5+f_ext_instr()
      //_|pipe
         //_@1
            assign PIPE_instr_a1[31:0] = PIPE_rand_a1[31:0];
            assign PIPE_is_load_store_a1 = {PIPE_instr_a1[14:12],PIPE_instr_a1[6:3]} ==? 7'b0100000 ||
                             {PIPE_instr_a1[14:12],PIPE_instr_a1[6:3]} ==? 7'b0100100;
   //_\end_source
   `line 23 "top.tlv" 2

   //...

   // Assert these to end simulation (before Makerchip cycle limit).
   assign passed = cyc_cnt > 40;
   assign failed = 1'b0;
//_\SV
   endmodule


// Undefine macros defined by SandPiper (in "top_gen.sv").
`undef BOGUS_USE
